version: '3.3'
services:
  app:
    container_name: laravel_app
    build:
      context: ./
    ports:
      - ${PORT}:80
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=ep-sweet-mud-a2sti4xp.eu-central-1.pg.koyeb.app
      - DB_PORT=5432
      - DB_DATABASE=koyebdb
      - DB_USERNAME=koyeb-adm
      - DB_PASSWORD=DRTj3IMUxnY5

