version: '3.3'
services:
  app:
    container_name: laravel_app
    build:
      context: ./
    ports:
      - ${PORT}:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=biblioteca2
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=biblioteca2
    # ports:
    #   - 8082:3306
volumes:
  mysql-data:
